// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-S9jmur6otd4Xhswc3V3snUW4-zrvJI',
    appId: '1:890299011378:web:878946ec4c50f07765072b',
    messagingSenderId: '890299011378',
    projectId: 'finder-love-281af',
    authDomain: 'finder-love-281af.firebaseapp.com',
    databaseURL: 'https://finder-love-281af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finder-love-281af.appspot.com',
    measurementId: 'G-J73L93XQ4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8kNpMKmsTq4CLQ6NizkcyoJs-KTq6_k',
    appId: '1:890299011378:android:e39b67c491944f0165072b',
    messagingSenderId: '890299011378',
    projectId: 'finder-love-281af',
    databaseURL: 'https://finder-love-281af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finder-love-281af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjqflGACt1JajKnWTCBTVUbt5fQH9FBQM',
    appId: '1:890299011378:ios:e3f6c3fbf24da37865072b',
    messagingSenderId: '890299011378',
    projectId: 'finder-love-281af',
    databaseURL: 'https://finder-love-281af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finder-love-281af.appspot.com',
    iosClientId: '890299011378-n2e04ru84h103eerod83d5f5oue0qnrf.apps.googleusercontent.com',
    iosBundleId: 'com.polvn.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjqflGACt1JajKnWTCBTVUbt5fQH9FBQM',
    appId: '1:890299011378:ios:dd4ddbb310c1a49065072b',
    messagingSenderId: '890299011378',
    projectId: 'finder-love-281af',
    databaseURL: 'https://finder-love-281af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finder-love-281af.appspot.com',
    iosClientId: '890299011378-nbvg5g5i7kkbub96t72c2e2oofsrmud6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
